### ISSUE TITLE
Support any JID as email address?

### ISSUE THREAD

**Issue by poVoq** [Moarc/smtp2xmpp#1]
Pretty cool project. I had the same concerns about the Go project, so nice to see a more maintainable project here.

Would it be possible to add a function that any JID can receive emails on the corresponding address?

**Comment by Moarc** [comment]
Done.

**Comment by Moarc** [comment]
Well that's a mess.

OTOH the first two commit messages were veritably unintuitive.

**Comment by poVoq** [comment]
Cool, thanks for adding this!
