### ISSUE TITLE
[Errno 88] Socket operation on non-socket

### ISSUE THREAD

**Issue by hubgitbb** [Moarc/smtp2xmpp#2]
Hi

i get the error above and dont know how to fix it. im on debian 10 with prosody . 

regards

**Comment by Moarc** [comment]
To fit my specific needs, I monkeypatched aiosmtpd.controller.InetMixin._create_server for a function that receives a socket using systemd socket activation. If you don't want this, you can comment out line 33 in smtp2xmpp.py.

Yes, ideally it should be an option in the config.

**Comment by Moarc** [comment]
Aaaand it's autodetected now.
