### ISSUE TITLE
[Errno 98] error while attempting to bind on address ('127.0.0.1', 25): address already in use

### ISSUE THREAD

**Issue by hubgitbb** [Moarc/smtp2xmpp#4]
hi again the 3th

well after fixing error 99 i did a server restart and then get error 98 . how can i fix the bind problem overall?

regards

**Comment by Moarc** [comment]
To bind ports below 1024 you have to give yourself capabilities (I'm not sure how though, for a binary you could use setcap, I don't know whether that would work for a Python script) or run the program as root.

btw you should restore the ::1 stuff in your /etc/hosts, I've had some unexpected issues arise from not having that config line in the past

**Comment by hubgitbb** [comment]
i run the script as root
and if i restore the ::1 stuff in /etc/hosts i get the error 99
any other ideas?

**Comment by hubgitbb** [comment]
`
Traceback (most recent call last):
  File "/usr/local/bin/smtp2xmpp.py", line 194, in <module>
    controller.begin()
  File "/usr/local/lib/python3.9/dist-packages/aiosmtpd/controller.py", line 370, in begin
    srv: AsyncServer = self.loop.run_until_complete(self.server_coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1494, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 99] error while attempting to bind on address ('::1', 25, 0, 0): cannot assign requested address
Done

`

**Comment by Moarc** [comment]
>any other ideas?

If you were getting error 98 "address already in use" before, that would mean something - another SMTP server - is listening on port 25. To check for that, you could use `netstat`.

**Comment by hubgitbb** [comment]
netstat did it
there was exim4 installed and listening on port 25. an apt remove exim4 fixed the problem.

thx
