### ISSUE TITLE
[Errno 111] Connect call failed ('127.0.0.1', 5348)

### ISSUE THREAD

**Issue by hubgitbb** [Moarc/smtp2xmpp#5]
hi

why does smtp2xmpp try to connect on port 5348?
Connection failed: [Errno 111] Connect call failed ('127.0.0.1', 5348)

my prosody server ist listeiing on default ports
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:5280            0.0.0.0:*               LISTEN      470/lua5.2
tcp        0      0 0.0.0.0:5281            0.0.0.0:*               LISTEN      470/lua5.2
tcp        0      0 0.0.0.0:5222            0.0.0.0:*               LISTEN      470/lua5.2
tcp6       0      0 :::5280                 :::*                    LISTEN      470/lua5.2
tcp6       0      0 :::5281                 :::*                    LISTEN      470/lua5.2
tcp6       0      0 :::5222                 :::*                    LISTEN      470/lua5.2

do i need to open port 5348 in prosody?

**Comment by Moarc** [comment]
It's a transport, and thus it connects to the Jabber server as a service, not as a client. See [TFM](https://prosody.im/doc/transports_and_gateways).

**Comment by hubgitbb** [comment]
i have setup my prosody config.lua with a new component and now it works. 
thx
